### ISSUE TITLE
unknown error 

### ISSUE THREAD

**Issue by ghost** [FoxMcloud5655/NEW-NUSGrabberGUI#9]
when i try to download any game the nusgrabbergui says that can't download the game because of a unknown error. This is happening while i'm using a old version because i want to solve an cemu issue. When i use the new version i can't handle it because it doesn't shows games in the titles but it shows things like eshop titles without the titles

**Comment by FoxMcloud5655** [comment]
So, let me get this straight.  There are two things, and they are as follows:
1.  You cannot download games because of an unknown error.
2.  You prefer using an old version of NEW-NUSGrabberGUI because the current version doesn't show games, but does show eshop titles?

I'm not quite sure what you want here.  In reference to the first item, attach a debug.log to your next comment, and let's see what the error is.
